/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/himanshu.glb -o src/components/HimanshuModel.jsx 
*/

import React, { useRef } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'

export function HimanshuModel(props) {
  const group = useRef()
  const { scene } = useGLTF('/himanshu.glb')
  
  const clone = React.useMemo(() => {
    const cloned = SkeletonUtils.clone(scene)
    cloned.traverse((child) => {
      if (child.isMesh) {
        child.frustumCulled = false // Prevent model from disappearing due to bounding box issues
        // Ensure materials are double sided just in case normals are flipped
        if (child.material) {
          child.material.side = THREE.DoubleSide
        }
      }
    })
    return cloned
  }, [scene])

  const { nodes } = useGraph(clone)

  // Interactive Cursor Tracking for the Head
  useFrame((state) => {
    if (nodes.Head) {
      // Calculate target rotation based on mouse position (-1 to 1)
      const targetX = state.mouse.y * 0.5; // Look up/down
      const targetY = state.mouse.x * 0.5; // Look left/right

      // Smoothly interpolate current rotation to target rotation
      nodes.Head.rotation.x = THREE.MathUtils.lerp(nodes.Head.rotation.x, targetX, 0.1);
      nodes.Head.rotation.z = THREE.MathUtils.lerp(nodes.Head.rotation.z, targetY, 0.1); // changed to z or y depending on blender orientation
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={clone} />
    </group>
  )
}

useGLTF.preload('/himanshu.glb')
