/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/flying+hoodie+figure+3d+model.glb -o src/components/MixamoModel.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/flying+hoodie+figure+3d+model.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Root} />
      <skinnedMesh geometry={nodes['tripo_node_703b61c5-43f4-4c48-9a91-a08a1c284516'].geometry} material={materials['tripo_mat_703b61c5-43f4-4c48-9a91-a08a1c284516']} skeleton={nodes['tripo_node_703b61c5-43f4-4c48-9a91-a08a1c284516'].skeleton} />
    </group>
  )
}

useGLTF.preload('/flying+hoodie+figure+3d+model.glb')
